title: Introduction to Chrome Extensions
author: Lillian Chen
email: lilyc5459@gmail.com
description: >
  This is just a look-of-the-land introduction on how to make chrome extensions.  
baseurl: "/crx"
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
